http://localhost:3000/search

###

http://localhost:3000/search/movie?q=Avatar

###

http://localhost:3000/search/person?q=Christopher

###
http://localhost:3000/search/episode?q=Pilot

###

http://localhost:3000/title/4

###

http://localhost:3000/title/4/cast

###

http://localhost:3000/title/1/awards